name: docs
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - pip

  - numpy
  - pandas

  - pytorch
  - ignite

  - mlflow
  - scikit-learn>=1.0

  - tqdm

  - sphinxcontrib-bibtex

  - pip:
    - molgrid
