name: Deploy gninatorch

on:
  push:
    branches:
      - master
    tags:
      - "*"
  release:
    types:
      - published

defaults:
  run:
    shell: bash -l {0}


jobs:
  build:
    if: "github.repository == 'RMeli/gnina-torch'"
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        shell: bash
        run: |
          python -m pip install build

      - name: Build Package
        shell: bash
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Publish on TestPyPI
        # Upload to testpypi on every tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.TESTPYPI_PWD }}
          repository_url: https://test.pypi.org/legacy/
